# -*- coding: utf-8 -*-
"""Inflow_Outflow_Hydrograph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjLVobTarHX2ZLvbEegSe3yrokKuXvSY

# Inflow and Outflow Hydrograph Simulation

Equations:

$$I(t) = \frac{I_p}{2}\left[1-\cos(\alpha t)\right]e^{kt}$$

$$O(t) = \frac{1}{e^{kt}}\int_0^t k \, I(t)\, e^{kt}\, dt$$

$$\alpha = \frac{2\pi}{\tau}$$

where:
- **Ip** = Peak Discharge (m3/s)
- **thau (τ)** = Time base (hr)
- **k** = storage/routing coefficient
- **dt** = time step (hr)
"""

!pip install ipywidgets -q

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import cumulative_trapezoid
import ipywidgets as widgets
from ipywidgets import interact, FloatSlider
from IPython.display import display

def inflow_outflow_hydrograph(t, Ip, thau, k):
    """
    Computes I(t) and O(t) based on the formula.
    t     : time array (hr)
    Ip    : Peak Discharge (m3/s)
    thau  : Time base (hr)
    k     : routing coefficient

    I(t) is a pure raised-cosine pulse, symmetric about t = thau/2,
    scaled so its maximum equals Ip exactly. It must NOT contain any
    exp(k*t) factor -- that belongs only to the O(t) routing integral,
    not to the shape of the inflow itself. Including it there shifts
    the peak later in time as k grows, which is not physical.
    """
    alpha = 2 * np.pi / thau

    # Pure raised-cosine inflow shape, valid only within [0, thau]
    I = np.where(t <= thau, (Ip / 2) * (1 - np.cos(alpha * t)), 0.0)

    # Outflow hydrograph O(t) = (1/e^(kt)) * integral(k * I(t) * e^(kt) dt)
    integrand = k * I * np.exp(k * t)
    integral = cumulative_trapezoid(integrand, t, initial=0)
    O = integral / np.exp(k * t)

    return I, O, alpha

def plot_hydrograph(Ip=60, thau=3.8, k=1.8, dt=0.05, t_end=4.0, review_time=2.85):
    t = np.arange(0, t_end + dt, dt)
    I, O, alpha = inflow_outflow_hydrograph(t, Ip, thau, k)

    # Point at the selected review time (like the 'Time' marker in Excel)
    idx = (np.abs(t - review_time)).argmin()
    t_point = t[idx]
    I_point = I[idx]
    O_point = O[idx]

    # Peak of each curve
    idx_Ipeak = np.argmax(I)
    idx_Opeak = np.argmax(O)

    plt.figure(figsize=(9, 5))
    plt.plot(t, I, label='I(t) - Inflow', color='tab:blue')
    plt.plot(t, O, label='O(t) - Outflow', color='tab:orange')

    plt.scatter([t_point], [I_point], color='blue', zorder=5, label=f'Point I(t) = {I_point:.2f}')
    plt.scatter([t_point], [O_point], color='red', zorder=5, label=f'Point O(t) = {O_point:.2f}')

    plt.annotate('Inflow', xy=(t[idx_Ipeak], I[idx_Ipeak]), xytext=(t[idx_Ipeak]-0.4, I[idx_Ipeak]-3))
    plt.annotate('Outflow', xy=(t[idx_Opeak], O[idx_Opeak]), xytext=(t[idx_Opeak]+0.2, O[idx_Opeak]-3))

    plt.xlabel('Time (hr)')
    plt.ylabel('Q (m3/s)')
    plt.title(f'Inflow and Outflow Hydrograph | Time = {t_point:.2f} hr')
    plt.grid(alpha=0.3)
    plt.legend(loc='upper left')
    plt.tight_layout()
    plt.savefig('hydrograph_plot.jpg', format='jpg', dpi=300, bbox_inches='tight', facecolor='white')
    plt.show()

    print(f"Alpha (α) = 2π/τ = {alpha:.3f}")
    print(f"At t = {t_point:.2f} hr -> I(t) = {I_point:.2f} m3/s ; O(t) = {O_point:.2f} m3/s")
    print(f"Peak Inflow  = {I[idx_Ipeak]:.2f} m3/s at t = {t[idx_Ipeak]:.2f} hr")
    print(f"Peak Outflow = {O[idx_Opeak]:.2f} m3/s at t = {t[idx_Opeak]:.2f} hr")

"""## Static simulation"""

plot_hydrograph(
    Ip=60,
    thau=3.8,
    k=1.8,
    dt=0.05,
    t_end=4.0,
    review_time=1.9)

"""## Interactive simulation
Move the sliders to change Ip, thau (τ), k, and the review time.
"""

interact(
    plot_hydrograph,
    Ip=FloatSlider(value=60, min=10, max=200, step=1, description='Ip (Peak Q)'),
    thau=FloatSlider(value=3.8, min=1, max=10, step=0.1, description='thau (τ)'),
    k=FloatSlider(value=1.8, min=0.1, max=5, step=0.1, description='k'),
    dt=FloatSlider(value=0.05, min=0.01, max=0.2, step=0.01, description='dt'),
    t_end=widgets.fixed(4.0),
    review_time=FloatSlider(value=2.9, min=0, max=10, step=0.05, description='Review time')
);

from google.colab import files

# Simpan gambar
plt.savefig('hydrograph_plot.jpg', format='jpg', dpi=300, bbox_inches='tight')
plt.show()

# Download otomatis ke komputer
files.download('hydrograph_plot.jpg')